platform :ios, '9.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


target 'QuoteDev' do
  pod 'Toaster'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  pod 'Kingfisher', '~> 4.0'
end

target 'QuoteDevWidget' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
end
