# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuoteDev' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuoteDev

pod 'Toaster'

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

pod 'Kingfisher', '~> 4.0'

end
